;; -*- coding: utf-8 -*-

(global-set-key (kbd "M-[") 'xah-cycle-font-previous)
(global-set-key (kbd "M-]") 'xah-cycle-font-next)

(global-set-key (kbd "M-1") 'xah-cycle-font-2)
(global-set-key (kbd "M-2") nil)
(global-set-key (kbd "M-3") nil)
(global-set-key (kbd "M-4") nil)
(global-set-key (kbd "M-5") nil)
(global-set-key (kbd "M-6") 'yank-pop)
(global-set-key (kbd "M-7") 'xah-previous-user-buffer)
(global-set-key (kbd "M-8") 'xah-next-user-buffer)
(global-set-key (kbd "M-9") 'xah-previous-emacs-buffer)
(global-set-key (kbd "M-0") 'xah-next-emacs-buffer)

(global-set-key (kbd "M-a") nil)
(global-set-key (kbd "M-b") nil)
(global-set-key (kbd "M-c") 'xah-cycle-hyphen-underscore-space)
(global-set-key (kbd "M-d") nil)
(global-set-key (kbd "M-e") nil)
(global-set-key (kbd "M-f") 'other-frame)
(global-set-key (kbd "M-g") 'xah-cycle-camel-style-case)
(global-set-key (kbd "M-h") nil)
(global-set-key (kbd "M-i") nil)
(global-set-key (kbd "M-j") nil)
(global-set-key (kbd "M-k") nil)
(global-set-key (kbd "M-l") nil)
(global-set-key (kbd "M-m") nil)
(global-set-key (kbd "M-n") nil)
(global-set-key (kbd "M-o") 'other-window)
(global-set-key (kbd "M-p") nil)
(global-set-key (kbd "M-q") nil)
(global-set-key (kbd "M-r") 'hippie-expand)
(global-set-key (kbd "M-s") nil)
(global-set-key (kbd "M-t") 'xah-toggle-letter-case)
(global-set-key (kbd "M-u") nil)
(global-set-key (kbd "M-v") nil)
;; (global-set-key (kbd "M-w") nil) ; was kill-ring-save, copy
;; (global-set-key (kbd "M-x") nil) ; was execute-extended-command
(global-set-key (kbd "M-y") nil)
(global-set-key (kbd "M-z") nil)
